[package]
name = "letterboxd-scrap"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper="0.16"
clap = { version = "4.5.9", features = ["derive"] }
